# Generated by Django 4.1.1 on 2022-10-09 10:21

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_catagory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName),
        ),
    ]
